
package vistas;

import Controller.FacturacionC;
import Model.FacturacionM;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian 
 */
public class Facturacion extends javax.swing.JFrame {

 
    public Facturacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Facturación - Hogar de paso Franluis");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/f.png")).getImage());
        jLabel1.add(panelAcompañante);
        panelAcompañante.setVisible(false);
        /*Login v=new Login();
        v.ventana=this;
        v.cronometro.start();*/
       
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PanelUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        jTextField9 = new javax.swing.JTextField();
        txtFechaEgreso = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        panelAcompañante = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCedulaAC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoAc = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreAc = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtFechaIngresoAc = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        txtFechaEgresoAc = new com.toedter.calendar.JDateChooser();
        checkAcompañante = new javax.swing.JCheckBox();
        aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cerrarSecion = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("N°");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, -1));

        PanelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));
        PanelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Nombre");
        PanelUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Cédula");
        PanelUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Apellido ");
        PanelUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("RH");
        PanelUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Egreso");
        PanelUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        PanelUsuario.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, -1));
        PanelUsuario.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, -1));
        PanelUsuario.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 120, -1));
        PanelUsuario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 130, -1));
        PanelUsuario.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));
        PanelUsuario.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 40, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Ingreso");
        PanelUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        PanelUsuario.add(txtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(null);
        PanelUsuario.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 20, -1));
        PanelUsuario.add(txtFechaEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Género");
        PanelUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
        PanelUsuario.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 60, -1));

        getContentPane().add(PanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 600, 170));

        panelAcompañante.setBackground(new java.awt.Color(255, 255, 255));
        panelAcompañante.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Acompañante"));
        panelAcompañante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Cédula");
        panelAcompañante.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        panelAcompañante.add(txtCedulaAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Apellido ");
        panelAcompañante.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        panelAcompañante.add(txtApellidoAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, -1));
        panelAcompañante.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 120, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setText("Nombre");
        panelAcompañante.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        panelAcompañante.add(txtNombreAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 130, -1));
        panelAcompañante.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("Género");
        panelAcompañante.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
        panelAcompañante.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 40, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setBorder(null);
        panelAcompañante.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 20, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("RH");
        panelAcompañante.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));
        panelAcompañante.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 60, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 255));
        jLabel20.setText("Ingreso");
        panelAcompañante.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        panelAcompañante.add(txtFechaIngresoAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 255));
        jLabel21.setText("Egreso");
        panelAcompañante.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        panelAcompañante.add(txtFechaEgresoAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        getContentPane().add(panelAcompañante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 600, 180));

        checkAcompañante.setBackground(new java.awt.Color(204, 204, 204));
        checkAcompañante.setForeground(new java.awt.Color(51, 153, 255));
        checkAcompañante.setText("Acompañante");
        checkAcompañante.setBorder(null);
        checkAcompañante.setContentAreaFilled(false);
        checkAcompañante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAcompañanteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkAcompañanteMousePressed(evt);
            }
        });
        checkAcompañante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAcompañanteActionPerformed(evt);
            }
        });
        getContentPane().add(checkAcompañante, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/btnAcF.png"))); // NOI18N
        aceptar.setBorder(null);
        aceptar.setBorderPainted(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/btnAceptarF_1.png"))); // NOI18N
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 110, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu/btnManual.PNG"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu/btnM.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 40));

        cerrarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/btnCS.PNG"))); // NOI18N
        cerrarSecion.setBorder(null);
        cerrarSecion.setBorderPainted(false);
        cerrarSecion.setContentAreaFilled(false);
        cerrarSecion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/btnCS1.png"))); // NOI18N
        cerrarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSecionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/btnMP.PNG"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/btnMP1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 290, 230, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Facturacion/Facturacion.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void validarCheckAcompañante() {
        if (checkAcompañante.isSelected()) {
            panelAcompañante.setVisible(true);
        } else if (checkAcompañante.isSelected() == false) {
            panelAcompañante.setVisible(false);
        }
    }

    private void checkAcompañanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAcompañanteActionPerformed

        validarCheckAcompañante();
    }//GEN-LAST:event_checkAcompañanteActionPerformed

    private void checkAcompañanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAcompañanteMouseClicked

    }//GEN-LAST:event_checkAcompañanteMouseClicked

    private void checkAcompañanteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAcompañanteMousePressed

    }//GEN-LAST:event_checkAcompañanteMousePressed

    private void cerrarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSecionActionPerformed
        Login obj = new Login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_cerrarSecionActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
      FacturacionC f = new FacturacionC();
        int ccacon =0;
       String fechaingresoA ="0000-00-00";
//      if (panelAcompañante.isVisible()) {
//           ccacon=Integer.parseInt(txtCedulaAC.getText()); 
//           fechaingresoA= txtFechaIngresoAc.getText();
//        }
//        try {
//            FacturacionM modelo = new FacturacionM(txtNombre.getText(), txtApellido.getText(), Integer.parseInt(txtCedula.getText()), 
//                    txtFechaIngreso.getText(), txtFechaEgreso.getText(),txtNombreAc.getText(), txtApellidoAc.getText(),
//                    ccacon,fechaingresoA ,0);
//            if (f.registrar(modelo)) {
//              JOptionPane.showMessageDialog(null, FacturacionC.mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
//              limpiar();
//            } else {
//                JOptionPane.showMessageDialog(null, FacturacionC.mensaje , "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_aceptarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cerrarSecion;
    private javax.swing.JCheckBox checkAcompañante;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelAcompañante;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoAc;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaAC;
    private com.toedter.calendar.JDateChooser txtFechaEgreso;
    private com.toedter.calendar.JDateChooser txtFechaEgresoAc;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private com.toedter.calendar.JDateChooser txtFechaIngresoAc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAc;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
//        txtFechaIngreso.setText("");
//        txtFechaEgreso.setText("");
        txtNombreAc.setText("");
        txtApellidoAc.setText("");
        txtCedulaAC.setText("");
//        txtFechaIngresoAc.setDate(date);
//        txtFechaEgresoAc.setText("");
        
 
    }
}
